ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER testmigration IDENTIFIED BY TestUser123;
GRANT CONNECT, RESOURCE TO testmigration;
GRANT CREATE TABLE TO testmigration;
GRANT CREATE SESSION TO testmigration;
ALTER USER testmigration QUOTA UNLIMITED ON USERS;
exit;