# Generated by Django 4.2 on 2024-03-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentry',
            name='action_test_long_one_field_is_long',
            field=models.CharField(db_column='action_test_long_one_fieldc443', max_length=64),
        ),
    ]
