# Generated by Django 4.2 on 2024-03-18 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditentry',
            old_name='action_test_long_one_field_is_long',
            new_name='action_test',
        ),
    ]
